let categoryBtnData = {
    data:[
        {
            title:'All',
            link:''
        },
        {
            title:'JavaScript',
            link:''
        },
        {
            title:'Podcasts',
            link:''
        },
        {
            title:'AI',
            link:''
        },
        {
            title:'C++',
            link:''
        },
        {
            title:'Music',
            link:''
        },
        {
            title:'Thoughts',
            link:''
        },
        {
            title:'Live',
            link:''
        },
        {
            title:'Array',
            link:''
        },
        {
            title:'Mixes',
            link:''
        },
        {
            title:'Asian Music',
            link:''
        },
        {
            title:'Recently uploaded',
            link:''
        },
        {
            title:'Watched',
            link:''
        },
        {
            title:'New to you',
            link:''
        }
    ]
}
export default categoryBtnData;